### PR TITLE
Bounding Box tool for rectangular segmentation. 

### LINKED ISSUE #164: Addition of additional tools - RectangularBox!
It'd be terrific if we could get some additional tools, in particular a rectangle box and circle.

### PR DESCRIPTION
**Pull request by mubashirhanif**
This tool allows to segment the images in the bounding box fashion, and some extra functionality, as mentioned in closes #164 .

There are a couple of assumptions:

1. Only one bounding box per annotation instance.
2. The bounding box co-ordinates(4 corners) can be found under segmentation attribute of the annotation in one of permutation of the following array. `[UpperLeft, UpperRight, BottomRight, BottomLeft]`, though opposing corners are always stored 2 indices apart. Such as if `UpperLeft` is at index 0 then `BottomRight` will be on  index 2.

This feature also adds some additional functionality to `SelectTool` such as:

1. You can now move the annotated bounding box, In future I'll try to add this functionality for polygon as well.
2. You can resize the bounding box in bounding box fashion.

### CODE REVIEW

**Comment by GeorgeSeif** [comment]
Is there any tutorial on how to use this tool?

**Comment by rbavery** [comment]
I'm also curious how to enable this, I just started using the most recent version today, but can't figure out how to use the bounding box tool and if moving polygons with select is implemented. awesome tool and thanks so much for developing it!

**Comment by jsbroks** [comment]
Moving a polygon is not implemented. You can move points of a polygon but not the entire ploygon.

Are you using the `stable` docker image or `lastest`

**Comment by mubashirhanif** [comment]
@rbavery the polygon movement is not yet implemented, I'll work on that feature as well once I have time. One problem in implementing the moving for polygon, is the way the polygon and `HitTest` works, for e.g. since the polygons have multiple closed components in them I don't know which closed component was selected so that I can move it. :)

**Pull request merged**
